spring:
  application:
    name: ajaxdemo
  datasource:
    url: jdbc:mysql://localhost:3306/ajaxdemo?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

server:
  port: 8888